// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXDeADEqKlgsHd5MVIWx0scxwUJnx5U4E',
    appId: '1:60370283373:web:441ab10f9538ddc251c864',
    messagingSenderId: '60370283373',
    projectId: 'bloodapp-bad48',
    authDomain: 'bloodapp-bad48.firebaseapp.com',
    storageBucket: 'bloodapp-bad48.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHqSoRssRU09439HJHO2EgHgqudyuzqJE',
    appId: '1:60370283373:android:191769459c25934951c864',
    messagingSenderId: '60370283373',
    projectId: 'bloodapp-bad48',
    storageBucket: 'bloodapp-bad48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhkD390Lb10PtK37aTwL6n3vlEnzyKv4o',
    appId: '1:60370283373:ios:64f34754b3b2f50951c864',
    messagingSenderId: '60370283373',
    projectId: 'bloodapp-bad48',
    storageBucket: 'bloodapp-bad48.appspot.com',
    iosBundleId: 'com.example.bloodDonateApp',
  );
}
